// lib/data.ts
//
// Sumber data SEMENTARA berupa array di memori. File ini sengaja dipisah
// dari lib/products.ts (logika query) supaya nanti kamu bisa mengganti isi
// file ini dengan koneksi ke MongoDB Atlas tanpa menyentuh halaman/komponen
// lain. Lihat README.md bagian "Menghubungkan ke MongoDB Atlas".

import { Category, Product } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "Elektronik", slug: "elektronik", icon: "Smartphone" },
  { id: "c2", name: "Fashion Wanita", slug: "fashion-wanita", icon: "Shirt" },
  { id: "c3", name: "Fashion Pria", slug: "fashion-pria", icon: "Footprints" },
  { id: "c4", name: "Rumah & Dapur", slug: "rumah-dapur", icon: "Home" },
  { id: "c5", name: "Kecantikan", slug: "kecantikan", icon: "Sparkles" },
  { id: "c6", name: "Olahraga", slug: "olahraga", icon: "Dumbbell" },
  { id: "c7", name: "Hobi & Mainan", slug: "hobi-mainan", icon: "Gamepad2" },
  { id: "c8", name: "Otomotif", slug: "otomotif", icon: "Car" },
];

const img = (id: string, n: number) =>
  `https://picsum.photos/seed/shopee-${id}-${n}/700/700`;

const avatar = (n: number) => `https://i.pravatar.cc/100?img=${n}`;

// Waktu flash sale dihitung relatif dari saat server pertama kali jalan,
// supaya hitung mundur di halaman tetap terasa "hidup" saat di-demo.
const hoursFromNow = (h: number) =>
  new Date(Date.now() + h * 60 * 60 * 1000).toISOString();

export const products: Product[] = [
  // ---------------- Elektronik ----------------
  {
    id: "p1",
    slug: "earbud-tws-bass-pro-x2",
    name: "Earbud TWS Bass Pro X2 Bluetooth 5.3 Noise Cancelling",
    price: 89000,
    originalPrice: 179000,
    discountPercent: 50,
    images: [img("p1", 1), img("p1", 2), img("p1", 3)],
    categorySlug: "elektronik",
    rating: 4.8,
    reviewCount: 3214,
    sold: 12500,
    stock: 86,
    location: "Jakarta Barat",
    shopName: "AudioTech Official",
    shopAvatar: avatar(12),
    description:
      "Earbud TWS dengan driver 13mm, dilengkapi active noise cancelling, tahan air IPX5, dan daya tahan baterai hingga 24 jam dengan case. Cocok untuk kerja, olahraga, dan commuting harian.",
    isFlashSale: true,
    flashSaleEndsAt: hoursFromNow(6),
    flashSaleStock: 200,
    flashSaleSold: 168,
  },
  {
    id: "p2",
    slug: "powerbank-20000mah-fast-charging",
    name: "Power Bank 20000mAh Fast Charging 22.5W Dual Output",
    price: 159000,
    images: [img("p2", 1), img("p2", 2), img("p2", 3)],
    categorySlug: "elektronik",
    rating: 4.7,
    reviewCount: 1820,
    sold: 6400,
    stock: 154,
    location: "Tangerang",
    shopName: "Gadget Central",
    shopAvatar: avatar(23),
    description:
      "Kapasitas besar 20000mAh dengan fast charging 22.5W, mendukung pengisian 2 perangkat sekaligus. Dilengkapi indikator LED digital dan bodi tahan banting.",
  },
  {
    id: "p3",
    slug: "smartwatch-fit-active-3",
    name: "Smartwatch Fit Active 3 - Layar AMOLED, Cek Detak Jantung",
    price: 249000,
    originalPrice: 399000,
    discountPercent: 38,
    images: [img("p3", 1), img("p3", 2), img("p3", 3)],
    categorySlug: "elektronik",
    rating: 4.6,
    reviewCount: 980,
    sold: 2300,
    stock: 62,
    location: "Surabaya",
    shopName: "WearTech ID",
    shopAvatar: avatar(34),
    description:
      "Smartwatch dengan layar AMOLED 1.43 inch, fitur pemantau detak jantung, SpO2, lebih dari 100 mode olahraga, dan tahan air 5ATM. Tahan baterai hingga 7 hari pemakaian normal.",
  },

  // ---------------- Fashion Wanita ----------------
  {
    id: "p4",
    slug: "dress-wanita-flowy-casual",
    name: "Dress Wanita Flowy Casual Premium Cotton",
    price: 75000,
    originalPrice: 150000,
    discountPercent: 50,
    images: [img("p4", 1), img("p4", 2), img("p4", 3)],
    categorySlug: "fashion-wanita",
    rating: 4.9,
    reviewCount: 4521,
    sold: 18900,
    stock: 210,
    location: "Bandung",
    shopName: "Lovira Fashion",
    shopAvatar: avatar(45),
    description:
      "Dress berbahan cotton premium yang ringan dan jatuh, nyaman dipakai sehari-hari maupun acara santai. Tersedia berbagai ukuran S-XL dengan jahitan rapi.",
    isFlashSale: true,
    flashSaleEndsAt: hoursFromNow(6),
    flashSaleStock: 300,
    flashSaleSold: 277,
  },
  {
    id: "p5",
    slug: "tas-selempang-wanita-korean-style",
    name: "Tas Selempang Wanita Korean Style Mini Bag",
    price: 65000,
    images: [img("p5", 1), img("p5", 2), img("p5", 3)],
    categorySlug: "fashion-wanita",
    rating: 4.7,
    reviewCount: 2104,
    sold: 9800,
    stock: 145,
    location: "Jakarta Selatan",
    shopName: "Lovira Fashion",
    shopAvatar: avatar(45),
    description:
      "Tas mini dengan tali selempang adjustable, bahan kulit sintetis anti air, cukup untuk dompet, HP, dan kosmetik kecil. Desain simpel cocok untuk segala outfit.",
  },
  {
    id: "p6",
    slug: "hijab-segiempat-voal-premium",
    name: "Hijab Segiempat Voal Premium Motif Polos",
    price: 28000,
    images: [img("p6", 1), img("p6", 2), img("p6", 3)],
    categorySlug: "fashion-wanita",
    rating: 4.8,
    reviewCount: 5230,
    sold: 21000,
    stock: 480,
    location: "Bandung",
    shopName: "Hijab Cantika",
    shopAvatar: avatar(51),
    description:
      "Hijab voal premium adem dan tidak mudah kusut, ukuran 110x110cm. Cocok untuk harian maupun acara formal, tersedia lebih dari 20 pilihan warna.",
  },

  // ---------------- Fashion Pria ----------------
  {
    id: "p7",
    slug: "kaos-polos-pria-cotton-combed",
    name: "Kaos Polos Pria Cotton Combed 30s Premium",
    price: 35000,
    images: [img("p7", 1), img("p7", 2), img("p7", 3)],
    categorySlug: "fashion-pria",
    rating: 4.8,
    reviewCount: 6700,
    sold: 25400,
    stock: 320,
    location: "Bandung",
    shopName: "Manstyle Apparel",
    shopAvatar: avatar(8),
    description:
      "Kaos polos berbahan cotton combed 30s, lembut dan menyerap keringat. Tersedia ukuran S-XXL dengan jahitan rantai rapi anti melar.",
  },
  {
    id: "p8",
    slug: "sneakers-pria-sporty-casual",
    name: "Sneakers Pria Sporty Casual Sole Empuk",
    price: 145000,
    originalPrice: 220000,
    discountPercent: 34,
    images: [img("p8", 1), img("p8", 2), img("p8", 3)],
    categorySlug: "fashion-pria",
    rating: 4.6,
    reviewCount: 1432,
    sold: 4100,
    stock: 98,
    location: "Jakarta Timur",
    shopName: "Manstyle Apparel",
    shopAvatar: avatar(8),
    description:
      "Sneakers dengan sol empuk dan ringan, upper breathable cocok untuk dipakai harian maupun olahraga ringan. Tersedia ukuran 39-44.",
  },
  {
    id: "p9",
    slug: "celana-chino-pria-slim-fit",
    name: "Celana Chino Pria Slim Fit Bahan Stretch",
    price: 69000,
    originalPrice: 120000,
    discountPercent: 43,
    images: [img("p9", 1), img("p9", 2), img("p9", 3)],
    categorySlug: "fashion-pria",
    rating: 4.7,
    reviewCount: 980,
    sold: 3200,
    stock: 76,
    location: "Semarang",
    shopName: "Urban Denim Co",
    shopAvatar: avatar(19),
    description:
      "Celana chino slim fit dengan bahan stretch yang nyaman bergerak, cocok untuk kerja maupun kasual. Tersedia warna hitam, navy, dan khaki.",
    isFlashSale: true,
    flashSaleEndsAt: hoursFromNow(6),
    flashSaleStock: 150,
    flashSaleSold: 94,
  },

  // ---------------- Rumah & Dapur ----------------
  {
    id: "p10",
    slug: "rak-organizer-serbaguna-susun",
    name: "Rak Organizer Serbaguna Susun 4 Tingkat",
    price: 89000,
    images: [img("p10", 1), img("p10", 2), img("p10", 3)],
    categorySlug: "rumah-dapur",
    rating: 4.7,
    reviewCount: 2310,
    sold: 7600,
    stock: 134,
    location: "Tangerang",
    shopName: "Rumah Rapi Store",
    shopAvatar: avatar(27),
    description:
      "Rak susun 4 tingkat berbahan plastik tebal anti karat, mudah dirakit tanpa alat tambahan. Cocok untuk dapur, kamar mandi, atau ruang cuci.",
  },
  {
    id: "p11",
    slug: "set-panci-anti-lengket-5-pcs",
    name: "Set Panci Anti Lengket 5 Pcs Granite Coating",
    price: 215000,
    originalPrice: 350000,
    discountPercent: 39,
    images: [img("p11", 1), img("p11", 2), img("p11", 3)],
    categorySlug: "rumah-dapur",
    rating: 4.8,
    reviewCount: 1540,
    sold: 3900,
    stock: 58,
    location: "Surabaya",
    shopName: "Dapur Idaman",
    shopAvatar: avatar(33),
    description:
      "Set panci dengan lapisan granite coating anti lengket, distribusi panas merata, dan gagang anti panas. Lengkap dengan tutup kaca tahan panas.",
  },
  {
    id: "p12",
    slug: "lampu-led-tumblr-dekorasi-kamar",
    name: "Lampu LED Tumblr Dekorasi Kamar USB 3 Meter",
    price: 22000,
    images: [img("p12", 1), img("p12", 2), img("p12", 3)],
    categorySlug: "rumah-dapur",
    rating: 4.6,
    reviewCount: 8900,
    sold: 31000,
    stock: 560,
    location: "Bandung",
    shopName: "Rumah Rapi Store",
    shopAvatar: avatar(27),
    description:
      "Lampu LED dekorasi dengan kabel USB, panjang 3 meter, cocok untuk menghias kamar, meja belajar, atau acara ulang tahun. Cahaya warm white yang hangat.",
  },

  // ---------------- Kecantikan ----------------
  {
    id: "p13",
    slug: "serum-niacinamide-brightening",
    name: "Serum Niacinamide 10% + Zinc Brightening 30ml",
    price: 39000,
    originalPrice: 65000,
    discountPercent: 40,
    images: [img("p13", 1), img("p13", 2), img("p13", 3)],
    categorySlug: "kecantikan",
    rating: 4.9,
    reviewCount: 12400,
    sold: 54000,
    stock: 640,
    location: "Jakarta Pusat",
    shopName: "Glowlab Beauty",
    shopAvatar: avatar(58),
    description:
      "Serum dengan kandungan Niacinamide 10% dan Zinc untuk membantu mencerahkan, menyamarkan pori, dan mengontrol minyak berlebih. Cocok untuk semua jenis kulit.",
    isFlashSale: true,
    flashSaleEndsAt: hoursFromNow(6),
    flashSaleStock: 400,
    flashSaleSold: 365,
  },
  {
    id: "p14",
    slug: "sunscreen-spf50-pa-gel-cream",
    name: "Sunscreen SPF 50 PA+++ Gel Cream Non Whitecast",
    price: 45000,
    images: [img("p14", 1), img("p14", 2), img("p14", 3)],
    categorySlug: "kecantikan",
    rating: 4.8,
    reviewCount: 9300,
    sold: 41000,
    stock: 410,
    location: "Jakarta Pusat",
    shopName: "Glowlab Beauty",
    shopAvatar: avatar(58),
    description:
      "Sunscreen dengan tekstur gel cream ringan, tidak meninggalkan whitecast, dan cepat menyerap. Melindungi kulit dari sinar UVA/UVB sepanjang hari.",
  },
  {
    id: "p15",
    slug: "masker-rambut-keratin-repair",
    name: "Masker Rambut Keratin Repair Treatment 250ml",
    price: 49000,
    images: [img("p15", 1), img("p15", 2), img("p15", 3)],
    categorySlug: "kecantikan",
    rating: 4.7,
    reviewCount: 2870,
    sold: 7400,
    stock: 220,
    location: "Yogyakarta",
    shopName: "Hairlux Studio",
    shopAvatar: avatar(61),
    description:
      "Masker rambut dengan kandungan keratin untuk memperbaiki rambut kering, rusak akibat catok/cat, membuat rambut lebih lembut dan berkilau.",
  },

  // ---------------- Olahraga ----------------
  {
    id: "p16",
    slug: "matras-yoga-anti-slip-8mm",
    name: "Matras Yoga Anti Slip 8mm + Tas Serut",
    price: 59000,
    images: [img("p16", 1), img("p16", 2), img("p16", 3)],
    categorySlug: "olahraga",
    rating: 4.8,
    reviewCount: 3100,
    sold: 8700,
    stock: 175,
    location: "Depok",
    shopName: "Fitlife Sport",
    shopAvatar: avatar(67),
    description:
      "Matras yoga tebal 8mm dengan permukaan anti slip, nyaman untuk yoga, pilates, maupun home workout. Sudah termasuk tas serut untuk dibawa kemana saja.",
  },
  {
    id: "p17",
    slug: "botol-minum-olahraga-1-liter",
    name: "Botol Minum Olahraga 1 Liter BPA Free Motivational",
    price: 35000,
    originalPrice: 55000,
    discountPercent: 36,
    images: [img("p17", 1), img("p17", 2), img("p17", 3)],
    categorySlug: "olahraga",
    rating: 4.7,
    reviewCount: 4500,
    sold: 15600,
    stock: 320,
    location: "Bekasi",
    shopName: "Fitlife Sport",
    shopAvatar: avatar(67),
    description:
      "Botol minum 1 liter dengan marking waktu motivasi, bahan BPA free, dan tutup anti tumpah. Cocok dibawa saat gym, lari, maupun aktivitas outdoor.",
    isFlashSale: true,
    flashSaleEndsAt: hoursFromNow(6),
    flashSaleStock: 250,
    flashSaleSold: 198,
  },
  {
    id: "p18",
    slug: "resistance-band-set-5-level",
    name: "Resistance Band Set 5 Level Latex Premium",
    price: 49000,
    images: [img("p18", 1), img("p18", 2), img("p18", 3)],
    categorySlug: "olahraga",
    rating: 4.6,
    reviewCount: 1980,
    sold: 5300,
    stock: 140,
    location: "Depok",
    shopName: "Fitlife Sport",
    shopAvatar: avatar(67),
    description:
      "Set resistance band dengan 5 level tingkat kekuatan berbeda, terbuat dari latex premium yang elastis dan tahan lama untuk latihan kekuatan di rumah.",
  },

  // ---------------- Hobi & Mainan ----------------
  {
    id: "p19",
    slug: "drone-mini-kamera-hd-lipat",
    name: "Drone Mini Kamera HD Lipat dengan Remote Control",
    price: 189000,
    originalPrice: 299000,
    discountPercent: 37,
    images: [img("p19", 1), img("p19", 2), img("p19", 3)],
    categorySlug: "hobi-mainan",
    rating: 4.5,
    reviewCount: 870,
    sold: 1900,
    stock: 47,
    location: "Jakarta Utara",
    shopName: "Toyland ID",
    shopAvatar: avatar(72),
    description:
      "Drone mini dengan kamera HD, desain lipat ringkas, dan kontrol stabil untuk pemula. Dilengkapi mode tahan ketinggian dan fitur one-key return.",
  },
  {
    id: "p20",
    slug: "lego-block-set-creative-500pcs",
    name: "Block Set Creative Bricks 500 Pcs Kompatibel",
    price: 99000,
    images: [img("p20", 1), img("p20", 2), img("p20", 3)],
    categorySlug: "hobi-mainan",
    rating: 4.8,
    reviewCount: 3650,
    sold: 9200,
    stock: 168,
    location: "Surabaya",
    shopName: "Toyland ID",
    shopAvatar: avatar(72),
    description:
      "Set balok kreatif 500 pcs yang kompatibel dengan brick populer lainnya, melatih kreativitas dan motorik anak. Disimpan dalam kotak storage praktis.",
  },
  {
    id: "p21",
    slug: "puzzle-1000-pcs-pemandangan",
    name: "Puzzle 1000 Pcs Pemandangan Alam Premium",
    price: 65000,
    originalPrice: 95000,
    discountPercent: 32,
    images: [img("p21", 1), img("p21", 2), img("p21", 3)],
    categorySlug: "hobi-mainan",
    rating: 4.7,
    reviewCount: 1240,
    sold: 2800,
    stock: 73,
    location: "Yogyakarta",
    shopName: "Toyland ID",
    shopAvatar: avatar(72),
    description:
      "Puzzle dengan 1000 keping bermotif pemandangan alam resolusi tinggi, dicetak di kertas tebal premium agar tidak mudah sobek dan warna tidak mudah pudar.",
    isFlashSale: true,
    flashSaleEndsAt: hoursFromNow(6),
    flashSaleStock: 120,
    flashSaleSold: 81,
  },

  // ---------------- Otomotif ----------------
  {
    id: "p22",
    slug: "kamera-dashcam-mobil-full-hd",
    name: "Kamera Dashcam Mobil Full HD Night Vision",
    price: 175000,
    images: [img("p22", 1), img("p22", 2), img("p22", 3)],
    categorySlug: "otomotif",
    rating: 4.6,
    reviewCount: 2050,
    sold: 4700,
    stock: 88,
    location: "Jakarta Barat",
    shopName: "Auto Gear Store",
    shopAvatar: avatar(81),
    description:
      "Dashcam dengan rekaman Full HD 1080p, night vision jernih, dan sudut pandang lebar 140 derajat. Dilengkapi G-sensor untuk deteksi tabrakan otomatis.",
  },
  {
    id: "p23",
    slug: "cover-jok-motor-anti-air",
    name: "Cover Jok Motor Anti Air Universal",
    price: 29000,
    images: [img("p23", 1), img("p23", 2), img("p23", 3)],
    categorySlug: "otomotif",
    rating: 4.7,
    reviewCount: 3300,
    sold: 11400,
    stock: 260,
    location: "Bandung",
    shopName: "Auto Gear Store",
    shopAvatar: avatar(81),
    description:
      "Cover jok motor universal berbahan anti air, melindungi jok dari panas, hujan, dan debu. Mudah dipasang dengan tali pengikat elastis.",
  },
  {
    id: "p24",
    slug: "lampu-led-motor-mobil-h4",
    name: "Lampu LED Motor/Mobil H4 Putih Terang 6000K",
    price: 55000,
    originalPrice: 85000,
    discountPercent: 35,
    images: [img("p24", 1), img("p24", 2), img("p24", 3)],
    categorySlug: "otomotif",
    rating: 4.6,
    reviewCount: 1670,
    sold: 5200,
    stock: 132,
    location: "Semarang",
    shopName: "Auto Gear Store",
    shopAvatar: avatar(81),
    description:
      "Lampu LED H4 dengan suhu warna 6000K putih terang, instalasi plug and play tanpa modifikasi tambahan, hemat daya dan tahan lama.",
  },
];
